# Generated by Django 5.0.1 on 2024-01-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_recruitment', models.DateField()),
                ('speciality', models.CharField(choices=[('GENERALIST', 'Generalist'), ('CARDIO', 'Cardiologist'), ('DERM', 'Dermatologist'), ('NEURO', 'Neurologist'), ('ORTHO', 'Orthopedic Surgeon'), ('ENT', 'Otolaryngologist (ENT Specialist)'), ('PEDI', 'Pediatrician'), ('PSYCH', 'Psychiatrist')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('full_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=20)),
                ('pre_appointement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_appointments', to='Project.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Project.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Project.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300)),
                ('classification', models.CharField(max_length=300)),
                ('symptoms', models.TextField()),
                ('treatement', models.TextField()),
                ('medica_advice', models.TextField()),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='Project.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medId', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('insurance_policy_number', models.CharField(max_length=50, unique=True)),
                ('insurance_expiry_date', models.DateField()),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('past_illnesses', models.TextField(blank=True, null=True)),
                ('surgeries', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='Project.patient')),
            ],
        ),
    ]
