# Generated by Django 5.0.1 on 2024-01-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pre_appointement',
        ),
    ]
