# Generated by Django 3.0.5 on 2024-01-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20240104_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='id',
            new_name='mid',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='pid',
        ),
    ]
