# Generated by Django 3.0.5 on 2024-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20240104_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
