# Generated by Django 3.0.5 on 2024-01-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20240104_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pre_appointment',
        ),
    ]
