# Generated by Django 4.2 on 2024-01-05 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_remove_appointment_pre_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(choices=[(datetime.datetime(1900, 1, 1, 9, 0), '9:00'), (datetime.datetime(1900, 1, 1, 10, 0), '10:00'), (datetime.datetime(1900, 1, 1, 11, 0), '11:00'), (datetime.datetime(1900, 1, 1, 12, 0), '12:00'), (datetime.datetime(1900, 1, 1, 13, 0), '13:00'), (datetime.datetime(1900, 1, 1, 14, 0), '14:00')], default=datetime.datetime(1900, 1, 1, 9, 0)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
