# Generated by Django 4.2 on 2024-01-05 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00')], default=datetime.time(9, 0)),
        ),
    ]
