# Generated by Django 4.2 on 2024-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20),
        ),
    ]
