# Generated by Django 4.2 on 2024-01-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_task'),
        ('Project', '0013_alter_appointment_state'),
    ]

    operations = [
    ]
